### ISSUE TITLE
Fix: array.ts should use Array as the primary type for inputs and outputs.

### ISSUE THREAD

**Issue by cryptogohan** [nullpub/fun#13]
I wouldn't say I feel strongly about this but I thought I'd at least put it up so people can vote on it.

For me the annoyance of having to change branches to all be readonly or safely cast the array to be writable again is not worth the bit of extra safety. Or I'd at least prefer there would be a separate module for `readonly` producing functions, like you often see with nonemptyarray. I'd also assume that all functions in Array don't mutate their inputs making the readonly less useful.

**Comment by baetheus** [comment]
@cryptogohan I've been thinking about making all inputs to array combinators take `ReadonlyArray` but returning `Array`. In general, this is useful for interaction with libraries that take Array instead of ReadonlyArray. In truth, most of these type mismatches occur because people specify Array inputs for functions that don't actually mutate.. which is really where the problem is.

Anyway, the two potential paths I can see are:

1. Make all exported array combinators have the form `<A>(inputAr: ReadonlyArray<A>) => Array<A>`.
2. Provide a typed identity function that strips the readonly (type unsafe). `<A>(inputAr: ReadonlyArray<A>) => inputAr as unknown as Array<A>`.
3. Both 1 and 2.

The issue with 1 is that it breaks with the intended use of `array.ts` for interop with x library outside of the control of fun. The issue with 2 is that it's not type safe.

I'd like to be pragmatic here but I'll have to think about more. I believe even fp-ts is going all in on ReadonlyArray.

**Comment by baetheus** [comment]
This change will see array.ts only target `Array<A>` as a type. I'm on the fence about ReadonlyArray and might consider it in the future, but it would essentially be re-exports of array.ts with different types.

**Comment by alextes** [comment]
FWIW I changed my mind on this and started marking things readonly as libs require. The effort is minimal, the type slightly more accurate.

I happen to be working with fp-ts right now and having separate modules for these works quite well imo. Still, keeping surface of this lib small to polish the core first makes sense to me.

I'd even go as far as saying this can be closed so you can focus on some other things I consider much more valuable adds.

**Comment by alextes** [comment]
oh btw, I am cryptogohan, I dropped the other account ✌️ .
