### ISSUE TITLE
Add zip function to array module

### ISSUE THREAD

**Issue by noverby** [nullpub/fun#6]
fp-ts provides a zip function in the array module.

Does fun provide something similar, or should I create a PR with a zip implementation.

**Comment by baetheus** [comment]
@noverby I veered away from adding all of the array and record helper functions that fp-ts has since there are a lot of possibilities in that space. Specifically, zip can be found in [lodash](https://deno.land/x/lodash@4.17.19) and [rambda](https://deno.land/x/rambda@v6.7.0).

That said, I'd be more than willing to review and likely merge a PR with zip for array, a good documentation blurb, and full test coverage. 👍

**Comment by baetheus** [comment]
I'd welcome a PR with this feature from a contributor but it's not on my list of features that I should be adding. If you have any more questions regarding zip, feel free to reopen this issue :)
